version: 1.0.9.{build}

for:
  -
    branches:
      only:
        - master
    build_script:
      - ps: .\build_script.ps1
    artifacts:
      - path: AMKFF_latest.zip
  -
    branches:
      only:
        - bleeding-edge
    build_script:
      - ps: .\build_script.ps1
    artifacts:
      - path: AMKFF_latestbeta.zip
  -
    branches:
      only:
        - AddmusicK1.0.9
    build_script:
      - ps: .\build_script.ps1
    artifacts:
      - path: AddmusicK1.0.9_latestRC.zip
  -
    branches:
      only:
        - AddmusicK1.0.9bleeding-edge
    build:
      verbosity: minimal
    artifacts:
      - path: AddmusicK1.0.9_latestRCbeta.zip
  -
    branches:
      except:
        - master
        - bleeding-edge
    only_commits:
      files:
        - src/
        - .appveyor.yml
    build_script:
      - ps: .\build_script.ps1
    artifacts:
      - path: AMKFF_testbuild.zip

configuration: Release

after_build:
  - ps: .\zip_script.ps1
  
deploy:
  - provider: FTP
    on:
      branch: master
    protocol: sftp
    host: www.atarismwc.com
    folder: html/amkff_releases/
    username: pi
    password:
      secure: N90u+68BQTm8IHH9p3O78A==
  - provider: FTP
    on:
      branch: bleeding-edge
    protocol: sftp
    host: www.atarismwc.com
    folder: html/amkff_releases/
    username: pi
    password:
      secure: N90u+68BQTm8IHH9p3O78A==
  - provider: FTP
    on:
      branch: AddmusicK1.0.9
    protocol: sftp
    host: www.atarismwc.com
    folder: html/amkff_releases/
    username: pi
    password:
      secure: N90u+68BQTm8IHH9p3O78A==
  - provider: FTP
    on:
      branch: AddmusicK1.0.9bleeding-edge
    protocol: sftp
    host: www.atarismwc.com
    folder: html/amkff_releases/
    username: pi
    password:
      secure: N90u+68BQTm8IHH9p3O78A==